version: '3.8'
services:
  postgres:
    container_name: pg
    image: postgres:alpine
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: simple_bank
    ports:
      - 5434:5432
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_SOURCE: "postgresql://root:root@postgres:5432/simple_bank?sslmode=disable"
    depends_on:
      - postgres
    links:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
  

