version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pg
    ports:
      - 5434:5432
